### PR TITLE
Ascii Art

### PR DESCRIPTION
**Pull request by lazerlipa**
this will kosherfy the ascii art it only works for completed days and I only tested on chrome and on some screen sizes it will shift the completed days a little 
image

### CODE REVIEW

**Review by llimos — CHANGES_REQUESTED** [review]
I see two issues if days are not fully completed in sequence
1. Days that aren't fully complete will have the treif art show through
2. The kosher art doesn't skip the rows that aren't complete, so it could look very stretched

**Comment by lazerlipa** [comment]
can you show me what you mean by 2 I cant see it since I completed all days

**Comment by lazerlipa** [comment]
I am giving up because I see that aoc changed the dom for the ascii art so I don't want to be busy fixing it for all updates

**Comment by llimos** [comment]
No worries, the ASCII art isn't usually so xmas-y anyway

**Comment by lazerlipa** [comment]
looks quite x-masy to me 
image

**Pull request closed without merging**
